### ISSUE TITLE
Can't read the english language files

### ISSUE THREAD

**Issue by Galixte** [alg5/newpmajax#1]
Hi,

i want to translate this extension in French but the english language files are not readable.

**Comment by alg5** [comment]
Hi. Galixte. sorry. this extension not yet ready :(

**Comment by Galixte** [comment]
Hi @alg5,

you will update this extension ?

**Comment by alg5** [comment]
yes sure

**Comment by Galixte** [comment]
Thanks i will waiting

**Comment by Galixte** [comment]
Hi @alg5,

any news about that extension ?

**Comment by alg5** [comment]
I intend to work on it soon

**Comment by Galixte** [comment]
Cool ! Thanks ;)

**Comment by Galixte** [comment]
Hi @alg,

it’s ready to test ?

**Comment by alg5** [comment]
yes, try it

**Comment by Galixte** [comment]
OK, thanks !-)

**Comment by Galixte** [comment]
This file is used ? https://github.com/alg5/newpmajax/blob/master/language/en/info_acp_live_search.php

Because the text is not readable.

**Comment by alg5** [comment]
no, it was mistake, I deleted it. thank you

**Comment by Galixte** [comment]
There is the same file in ru folder: https://github.com/alg5/newpmajax/blob/master/language/ru/info_acp_live_search.php

**Comment by alg5** [comment]
ups...deleted too

**Comment by alg5** [comment]
the same story :(

**Comment by Galixte** [comment]
what’s story ?

**Comment by alg5** [comment]
unused lang files
 I fix now all issues

**Comment by Galixte** [comment]
yes thanks ;)
