### ISSUE TITLE
Difference between two language keys

### ISSUE THREAD

**Issue by Galixte** [alg5/newpmajax#2]
Hi @alg5,

what is the difference between those two language keys ?

```
    'PMAJAX_USER_REMOVED_NO_PERMISSION' => 'User  %s couldn’t be added, as this user do not have permission to read private messages.',
    'PMAJAX_USER_REMOVED_NO_PM' => 'User  %s couldn’t be added, as  this user do not have permission to read private messages.',
```

**Comment by vendethiel** [comment]
(also, it should be "this user does")

**Comment by alg5** [comment]
it will be
    'PMAJAX_USER_REMOVED_NO_PERMISSION' => 'User  %s couldn’t be added, as this user does not have permission to read private messages.',
    'PMAJAX_USER_REMOVED_NO_PM' => 'User  %s couldn’t be added, as  this user have disabled private message receipt.',

**Comment by Galixte** [comment]
ok thanks.

**Comment by alg5** [comment]
fixed
vendethiel, thanks

**Comment by vendethiel** [comment]
Keep up the good work :)

**Comment by Galixte** [comment]
ok thanks
