### ISSUE TITLE
version.json doesn’t found

### ISSUE THREAD

**Issue by Galixte** [alg5/newpmajax#4]
Hi @alg5,

i have this error in ACP:

```
Failed to obtain latest version information.
The requested file could not be found: version.json
Re-Check version
```

I suppose that it’s this: https://github.com/alg5/newpmajax/blob/master/composer.json#L31.

**Comment by alg5** [comment]
added

**Comment by Galixte** [comment]
not fixed. it’s in details page in customize tab in acp.

**Comment by Galixte** [comment]
@alg5, could you fix this ?

**Comment by alg5** [comment]
fixed, thanks

**Comment by Galixte** [comment]
Hi @alg5,

there is no file at the address: http://alg5.github.io/version/newpmajax.json, see that: https://github.com/alg5/newpmajax/commit/74ca7cc9dffe4c7d04b6d30f970745f898321d01#commitcomment-12879590.

**Comment by Galixte** [comment]
After doing the correction, i have this message:

```
Failed to obtain latest version information.
Re-Check version
```

**Comment by alg5** [comment]
fixed

**Comment by Galixte** [comment]
Hi @alg5,

i have always this message:

```
Failed to obtain latest version information.
Re-Check version
```

For all your extensions, go in ACP => EXTENSIONS => Manage extensions => on line of your extension click on “Details” and the message is displayed.

Maybe it’s the read access of the versions json files which are not right on GitHub: https://github.com/alg5/alg5.github.io ? See this commit which shows an example of changing permissions on a file: https://github.com/VSEphpbb/abbc3/commit/e83347cb9d57d9b0005976821c71593f364f8b0d.

**Comment by alg5** [comment]
I don't know/ Can y read this file ?https://github.com/alg5/alg5.github.io/blob/master/versions/newpmajax.json

**Comment by Galixte** [comment]
Of course with our browser we can read those versions json files, but there is a problem for the script of phpBB to access to those files.

I suggest you the permissions of file, like the link of the commit that i mentionned.

Or maybe, it’s the strange red colour displayed which is the cause: https://github.com/alg5/alg5.github.io/blob/master/versions/newpmajax.json. I don’t know the meaning of the red colour on code for GitHub.

**Comment by Galixte** [comment]
I have edited the last link.

**Comment by alg5** [comment]
may be space instead tab or vise versa?

**Comment by Galixte** [comment]
I think that i have fixed all versions json files here: https://github.com/alg5/alg5.github.io/pull/1.

**Comment by alg5** [comment]
thank u very much, @Galixte !

**Comment by Galixte** [comment]
Hi,

it’s solved for me. ;)

**Comment by alg5** [comment]
yes, it;s great!!!!
