### ISSUE TITLE
Empty file and used or not used files

### ISSUE THREAD

**Issue by Galixte** [alg5/newpmajax#5]
Hi @alg5,

i think you have to check the minimum, yours files in this extension to know what are used and what are not used to delete them.

Other empty files found:
- https://github.com/alg5/newpmajax/blob/master/styles/all/template/event/overall_header_head_append.html
- https://github.com/alg5/newpmajax/blob/master/styles/prosilver/theme/newpmajax.css

Those files are used ?
- https://github.com/alg5/newpmajax/blob/master/styles/prosilver/theme/images/show-hide.png
- https://github.com/alg5/newpmajax/blob/master/styles/prosilver/template/event/posting_pm_header_find_username_after.html <= for what display “qwerty” ? And for me « Azerty » ?  :P
- empty file https://github.com/alg5/newpmajax/blob/master/styles/prosilver/theme/newpmajax.css but it’s called by other HTML files, should contain code ?.

**Comment by alg5** [comment]
fixed

**Comment by Galixte** [comment]
thanks
