### ISSUE TITLE
Adding username + useless “Add” button

### ISSUE THREAD

**Issue by Galixte** [alg5/newpmajax#7]
Hi @alg5,

when i enter the begining of a username in “Quick search:” area, the username is displayed and if i click on it, the username appears in “Add recipients:” area, but above the “PM icon:” area i don’t see the “Recipients:” area with the username displayed.

Of course if i click on “Preview” button under the message, the username will appear in the “Recipients:” area.

All of this to say, that the “Add” button becomes useless, it’s confused for the user to see this button but can not use it.

**Comment by alg5** [comment]
1. quick search user makes another extension  ( LiveSearch)
2. I don;t understand this problem.
   If i clicked the username it appears  in the area "Add recipients"
   if i clicked  the “Add” button or the  the “Bcc” button. all usernames from area move to recipients

If ext LiveSearch not exists or off, will be search by clicked on link "Find a member"

**Comment by Galixte** [comment]
Before, the add button wasn’t working, now it’s fixed thanks
