### ISSUE TITLE
Live search extension is used by this extension

### ISSUE THREAD

**Issue by Galixte** [alg5/newpmajax#8]
Hi @alg5,

i say a mistake if i think this extension uses this other extension https://github.com/alg5/liveSearch to search the usernames ?

Ok, if i remove Live Search extension, this extension becomes useless.

**Comment by alg5** [comment]
no sure, There is no connection between the work of ext "LiveSearch" and this ext "newpmajax"
LiveSearch only adds quick search user on the page "Compose PM"
I think maybe it will meaningful remove this search from LiveSearch  and add to newpmajax

**Comment by Galixte** [comment]
ok thanks
